### ISSUE TITLE
You left your API key in the code

### ISSUE THREAD

**Issue by wayneconnolly** [codemakerss/Alpha_Vantage_API#1]
Hi - just telling you incase you didn't know.

https://github.com/codemakerss/FInancial-Data-Project/blob/main/API_Data_Retrieve.py#L94

**Comment by codemakerss** [comment]
Thank you so much for mention that! I have already fix it.

**Comment by codemakerss** [comment]
> Hi - just telling you incase you didn't know.
> 
> https://github.com/codemakerss/FInancial-Data-Project/blob/main/API_Data_Retrieve.py#L94

Thank you so much for mention that! I have already fixed it.

**Comment by wayneconnolly** [comment]
Great- have you got this working? I keep getting this error:

`Alpha_VantageAPI = Alpha_VantageAPI.GetListingDelistingStatus()
  File "/app/API_Data_Retrieve.py", line 172, in GetListingDelistingStatus
    r = requests.get(CSV_URL)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=LISTING_STATUS&apikey=XXX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0322e09160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
`

I started converting it to a dockerized application if you are interested?

**Comment by codemakerss** [comment]
> Great- have you got this working? I keep getting this error:
> 
> `Alpha_VantageAPI = Alpha_VantageAPI.GetListingDelistingStatus() File "/app/API_Data_Retrieve.py", line 172, in GetListingDelistingStatus r = requests.get(CSV_URL) File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get return request('get', url, params=params, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request return session.request(method=method, url=url, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 529, in request resp = self.send(prep, **send_kwargs) File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 645, in send r = adapter.send(request, **kwargs) File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 519, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=LISTING_STATUS&apikey=XXX (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0322e09160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')) `
> 
> I started converting it to a dockerized application if you are interested?

It is  because of 500 maximum tries for the free alpha vantage API key. If you want 500  more  tries, you can go visit this website: https://www.alphavantage.co/premium/. Also there is an alternative way to avoid that is to apply for more than 2 or 3 API keys. You can get your free api key through https://www.alphavantage.co/support/#api-key.

**Comment by wayneconnolly** [comment]
I now have a premium account so its working. I think I figured out your structure a bit more now.

```
Alpha_VantageAPI = Alpha_VantageAPI(apikey)
df = Alpha_VantageAPI.GetListingDelistingStatus()
print(df)
MySQL_Connection = MySQL_Connection(apikey,host=host,user=user,password=password,database=database)
Data_to_SQL.insert_data(data=df,table_name="listinganddelisting",symbol="")
```

but i cant seem to write the symbols to the table (tables have all been created successfully).

```
TypeError: insert_data() missing 1 required positional argument: 'self'

```

**Comment by codemakerss** [comment]
> I now have a premium account so its working. I think I figured out your structure a bit more now.
> 
> ```
> Alpha_VantageAPI = Alpha_VantageAPI(apikey)
> df = Alpha_VantageAPI.GetListingDelistingStatus()
> print(df)
> MySQL_Connection = MySQL_Connection(apikey,host=host,user=user,password=password,database=database)
> Data_to_SQL.insert_data(data=df,table_name="listinganddelisting",symbol="")
> ```
> 
> but i cant seem to write the symbols to the table (tables have all been created successfully).
> 
> ```
> TypeError: insert_data() missing 1 required positional argument: 'self'
> ```

I think you forgot to initialize the class of Data_to_SQL, which means you have to add : 
Data_to_SQL = Data_to_SQL(Alpha_VantageAPI)  after the initialization of MySQL_Connection class method.

**Comment by wayneconnolly** [comment]
Thank-you. Yes- that works now. Terrific.

Is there a way to update all daily, weekly, monthly from the listinganddelisting table? I have premium!

I have had no luck.

**Comment by wayneconnolly** [comment]
Thanks and good luck. This is a nice start but I am going to play with something else.

**Comment by codemakerss** [comment]
> Thank-you. Yes- that works now. Terrific.
> 
> Is there a way to update all daily, weekly, monthly from the listinganddelisting table? I have premium!
> 
> I have had no luck.

You could achieve those daily, weeks, monthly data from API_Data_Retrieve.py. There are couple of functions there to help you get those data.
Example code:
Alpha_VantageAPI = Alpha_VantageAPI(apikey)
daily_data = Alpha_VantageAPI.GetDailyStockPrice("IBM")
print(daily_data)

**Comment by codemakerss** [comment]
> Thanks and good luck. This is a nice start but I am going to play with something else.

No problem!
